js-data-types-exercises
js-tasks-ru/js-20220905_dolphi pull request #2
Opened 2022-09-10 16:23 UTC by Alpha-Dolphi

2022-09-10 16:24 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-09-11 14:28 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +export function sortStrings(arr, param = 'asc') {
👍 good

2022-09-11 14:29 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +    for (const ind in fields) {
цикл `for...in` применяется по итерации по объектам и имеет ряд недостатков, по массивам же следует проводить итерацию с помощью `for...of`

2022-09-11 14:29 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +            newObj[fields[ind]] = obj[fields[ind]]    ;
`;` куда-то убежала...                               далеко

2022-09-11 14:30 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +            delete obj[fields[ind]];
использовать delete в связке с объектом не рекомендуется, даже при копировании объекта {...obj} происходит shallow copy - поверхностное копирование, поэтому удаление может привести к весьма неожиданным последствиям

2022-09-11 14:30 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +        if (obj.hasOwnProperty(fields[ind])) {
не используйте на практике `hasOwnProperty`, предпочтение следует отдавать методу `hasOwn`

2022-09-11 14:30 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2022-09-12 19:10 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-09-13 12:30 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-09-13 14:20 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-09-14 21:25 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +'use strict';
'use strict' тут не нужен, в модулях этот режим включен по умолчанию

2022-09-14 21:25 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +    return (obj) => !Object.keys(obj).length ? undefined : path.split('.').reduce((arr, i) => arr[i], obj);
было бы неплохо вынести `path.split('.')` в родительскую функцию, иначе данная операция будет выполняться каждый раз при вызове геттера, хотя данное значение требуется рассчитать только один раз при создании геттера

2022-09-14 21:25 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +    return (obj) => !Object.keys(obj).length ? undefined : path.split('.').reduce((arr, i) => arr[i], obj);
помните, что явно `undefined` мы не возвращаем

2022-09-14 21:25 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
> +    if (obj === undefined) return undefined;
просто `return`

2022-09-14 21:26 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/3-trim-symbols/index.js
> +    let prevSymb = string[0];
используйте деструктурирование:
```
let [prevSymb] = string;
```

2022-09-14 21:27 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/3-trim-symbols/index.js
> +        if (string[i] != prevSymb) {
`!=` - нет такого оператора в JS

2022-09-14 21:28 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/3-trim-symbols/index.js
> +    return lastIndexes.reduce((result, Val) => ( (string[Val+1] != string[Val]) ? (result + string.slice(Val, Val+1)) : (result + string.slice(Val, Val+size))), "");
c заглавной буквы можно именовать только классы или ф-ции конструкторы

2022-09-14 21:29 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/3-trim-symbols/index.js
> +    return lastIndexes.reduce((result, Val) => ( (string[Val+1] != string[Val]) ? (result + string.slice(Val, Val+1)) : (result + string.slice(Val, Val+size))), "");
что происходит в строке #20 очень сложно понять. Может стоит некоторым значениям дать имена, например:
```
const nextChar = string[Val+1];
const currentChar = string[Val];
```

2022-09-14 21:30 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/4-uniq/index.js
> +    const set = new Set(arr);
если используете `Set` то решение должно выглядеть короче:
```
return [...new Set(arr)]
```

2022-09-14 21:30 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/4-uniq/index.js
> +    for (let symb of arr) { set.add(symb); }
подумайте какие есть преимущества у `Array.from` по сравнению с спред-синтаксисом:
```
return [...new Set(arr)]
```

2022-09-14 21:31 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2022-09-15 11:39 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-09-15 16:13 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +        const finalPath = path.split('.');
good 👍 лайк за замыкание

2022-09-15 16:13 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +        return finalPath.reduce((arr, i) => arr[i], obj);
подумайте, можно ли сделать `break` в `reduce`?
а в `for...of`?

2022-09-15 16:14 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/3-trim-symbols/index.js
> +        (string[val+1] != string[val]) ?
`!=` нет такого оператора в JS

2022-09-15 16:14 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/4-uniq/index.js
> +    return [...new Set(arr)]
подумайте какие есть преимущества у `Array.from` по сравнению с спред-синтаксисом:
```
return [...new Set(arr)]
```

2022-09-15 16:14 UTC, dosandk approved these changes
good 👍

2022-09-15 16:15 UTC, merged